<script language="JavaScript" type="text/javascript" src="/scripts/jquery.php.js"></script>

<script language="JavaScript" type="text/javascript">
    function writeTurn()
    {
        var ats    = $("select[name='ats_id']").val();
        var pcross = $("input[name='pcross']").val();
		var cname  = $("input[name='contact_name']").val();
		var cphone = $("input[name='contact_phone']").val();

        $.php("/turn/add", {
                    ats_id: ats,
                    pcross: pcross,
                    contact_name: cname,
                    contact_phone: cphone
        });
    }
</script>

<table border="0">
<tr>
	<th><h1>Отдел продаж. Добавление | </h1> </th>
	<th> <form action="/turn/index"> <input type="submit"/ value="журнал"></form></th>
</tr>
</table>
<br />
<br />
<center>
	<div id="turn_add_id">

	</div>
</center>
<center>
<form action="#" method="post">
<table border="0" width="100%">
<tr>
	<td>
		<div class="clear"></div>
		<?php echo $this->form->pcross; ?>
		<div class="clear"></div>
		<?php echo $this->form->ats_id; ?>
		<div class="clear"></div>
		<?php echo $this->form->contact_name; ?>
		<div class="clear"></div>
		<?php echo $this->form->contact_phone; ?>
		<div class="clear"></div>
		<?php echo $this->form->userid; ?>
	</td>
</tr>
<tr>
	<td align="center">
		<input type="button" onclick='writeTurn()' value="сохранить" />
	</td>
</tr>
</table>

</form>
</center>