<h1>Формирование счета</h1>
<br />
<br />
<center>
	<?= $this->form; ?>
</center>
<div class='clear'></div>
<br />
<br />
<center>
	<?
	if ($this->message)
	{
		print '<h2>' . $this->message . '</h2>';
	} 
	?>
</center>
<script type="text/javascript">
function documentChanged()
{
	var selected = $('#document_type').val();
	if (selected == 1) {
		$('#without_prepay-label').show();
		$('#without_prepay-element').show();
	}
	else {
		$('#without_prepay').removeAttr('checked');
		$('#without_prepay-label').hide();
		$('#without_prepay-element').hide();
	}
}

$('#document_type').change(documentChanged);

documentChanged();
</script>