<h1>Бухгалтерия. Корректировка САЛЬДО</h1>

<br />
<br />
<center>
	<form action="" method="post">
		ID клиента: <input type="text" name="client_id" />
		На дату: <input type="text" name="sdate" value="2010-01-01" />
		<input type="submit" value="найти" name="btn1" />
	</form>
</center>

<br />
<br />


<br />
<table class="list" cellpadding="3" cellspacing="0">
    <tr>
        <th class="list_head">N</th>
        <th class="list_head">Наименование</th>
        <th class="list_head" style="width:15%;">Баланс</th>
        <th class="list_head">Действие</th>
    </tr>
<?php
if ( count($this->data) == 0 )
{
    ?>
    <tr>
        <td colspan="9" class="list_row center">
            Не найдено
        </td>
    </tr>

    <?
}
else
{
    $counter = 1;

    foreach ($this->data as $info)
    {
    ?>
        <tr class='list_tr' onMouseOver="this.setAttribute('class', 'list_tr_hover')" onMouseOut="this.setAttribute('class', 'list_tr')">
            <td class="list_row"><?= $counter++; ?></td>
            <td class="list_row">
            		<?= $info['client_name']; ?>
            </td>
            <td class="list_row"><?= $info['ballance']; ?></td>
            <td class="list_row">
            	<form action="/Saldo/set-saldo" method="post" >
            		<input type="hidden" name="b_id" value="<?= $info['id']; ?>" />
            		<input type="hidden" name="clientid" value="<?= $info['clientid']; ?>" />
            		<input type="text" name="newsaldo" value="" />
            		<input type="submit" name="btn1" value="установить" />
            	</form>
            </td>

        </tr>
    <?
        $price = $price + $info['tarif_price'];
    }

}
?>
</table>