<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="author" content="Abilov Marat, Tsoy Alexey" />
    <title>АСР "SHARQ". Администрирование</title>
    <link rel="stylesheet" type="text/css" href="/styles/global.css" />
	<script language="JavaScript" type="text/javascript" src="/scripts/jquery.js"></script>
</head>
<body>
    <?php echo $this->layout()->content ?>
</body>
</html>