<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="author" content="Abilov Marat, Tsoy Alexey" />
    <title>АСР "SHARQ". Администрирование</title>
    <link rel="stylesheet" type="text/css" href="/styles/global.css" />
	<script language="JavaScript" type="text/javascript" src="/scripts/jquery.js"></script>
</head>
<body>

Трафик. IP (<?= $this->ipaddress ?>)
<br />
<br />
<?= $this->form; ?>

<br />
<br />
<br />

Входящий: <?= number_format($this->getTotal['bytes_in'], 2, ',', ' ') ?> МБ
Исходящий: <?= number_format($this->getTotal['bytes_out'], 2, ',', ' ') ?> МБ
<br />
Итого: <?= number_format($this->getTotal['total'], 2, ',', ' ') ?> МБ
</table>

<br />

<br />
<table class="list" cellpadding="3" cellspacing="0">
    <tr>
        <th class="list_head">N</th>
        <th class="list_head">Дата</th>
        <th class="list_head">Время</th>
        <th class="list_head" style="width:15%;">IP</th>
        <th class="list_head">Вх. траф.</th>
        <th class="list_head">Исх. траф</th>
    </tr>
<?php
if ( count($this->getList) == 0 )
{
    ?>
    <tr>
        <td colspan="9" class="list_row center">
            Не найдено
        </td>
    </tr>

    <?
}
else
{
    $counter = 1;

    foreach ($this->getList as $row)
    {
    ?>
        <tr class='list_tr' onMouseOver="this.setAttribute('class', 'list_tr_hover')" onMouseOut="this.setAttribute('class', 'list_tr')">
            <td class="list_row"><?= $counter++; ?></td>
            <td class="list_row"><?= date('d.m.Y', strtotime($row['date_time'])); ?></td>
            <td class="list_row">
            	<?= date('H:i', strtotime($row['start_time'])) . ' - ' . date('H:i', strtotime($row['end_time']));  ?>
            </td>
            <td class="list_row"><?= $row['ip_address']; ?></td>
            <td class="list_row right"><?= number_format($row['bytes_in'], 2, ',', ' '); ?></td>
            <td class="list_row right"><?= number_format($row['bytes_out'], 2, ',', ' '); ?></td>
        </tr>
        <?
    }
}
?>
</table>





</body>
</html>