<script language="JavaScript" type="text/javascript">
function searchTeh()
{
	var param = $('#param').val();
	var value = $('#value').val();
	redirect('/searchclient/index/param/' + param + '/value/' + value);
	return false;
}
</script>
<h1><b>Поиск клиента. Абонентский отдел</b></h1>
<br/>

<form action="/Searchclient/index" method="post" onsubmit="return searchTeh()">

<center>
    <table cellpadding="3" cellspacing="0">
        <tr>
            <td class="row">Найти клиента</td>
            <td class="row">
                <?
				$options = array(
					'points.u_login'		=> 'по логину',
					'clients.client_id'		=> 'по ID клиента',
					'points.pcross'			=> 'по телефону кроссировки',
					'clients.phone'         => 'по конт. телефону',
					'clients.client_name'	=> 'по наименованию',
					'ats_list.name'			=> 'по АТС'
				);

                print "<select id='param'>";
                print FormHelper::getSelectOptions($options, $this->param);
                print "</select>";
                ?>
            </td>
            <td class="row">
                <input type="text" id="value" value="<?= $this->value; ?>" />
            </td>
            <td class="row">
                <input type="submit" value="Поиск" />
            </td>
        </tr>
    </table>
</center>
</form>
<br/>
<br />
<?
if ( $this->clients )
{
    ?>
    <table class="list" cellpadding="3" cellspacing="0">
        <tr>
            <th class="list_head">Действие</th>
            <th class="list_head">N</th>
            <th class="list_head">Название</th>
            <th class="list_head">Баланс</th>
            <th class="list_head">Логин</th>
            <th class="list_head">Контактный телефон</th>
            <th class="list_head">Телефон кроссировки</th>
            <th class="list_head">АТС</th>
            <th class="list_head">Порт</th>
            <th class="list_head">Идентификатор</th>
        </tr>
        <?
        if( count($this->clients) == 0 )
        {
            ?>
            <tr>
                <td class="list_row center" colspan="8">Не найдено ни одного клиента</td>
            </tr>
            <?
        }

        $counter = $this->start;

        foreach($this->clients as $client)
        {
            ?>
            <tr class='list_tr' onMouseOver="this.setAttribute('class', 'list_tr_hover')" onMouseOut="this.setAttribute('class', 'list_tr')">
                <td class="list_row">
                	<a href="/Clientinfo/index/clientid/<?= $client['client_id']; ?>/pointid/<?= $client['point_id']; ?>" >
							<img id="decor_a" border="0" src="/images/edit.png" width="25" height="25" />
					</a>
                </td>
                <td class="list_row"><?= $counter++; ?></td>
                <td class="list_row"><?= $client['client_name']; ?></td>
                <td class="list_row" align="right"><b><?= number_format($client['ballance'], 2, '.', ' '); ?></b></td>
                <td class="list_row"><?= $client['u_login']; ?></td>
                <td class="list_row"><?= $client['contact_phone']; ?></td>
                <td class="list_row"><?= $client['cross_phone']; ?></td>
                <td class="list_row"><?= $client['ats']; ?></td>
                <td class="list_row">
                	<?php
						if($client['state'] == 1)
						{
							$state_word = "Вкл.";
						}
						else
						{
							$state_word = "Выкл.";
						}
                	?>
                	<b><?= $state_word; ?></b>
                </td>
                <td class="list_row"><?= $client['client_id']; ?></td>
            </tr>
            <?
        }
        ?>
    </table>
    <br/>
	<br/>
	<center>
		<?= $this->paginationControl($this->clients, 'Sliding', '/my_pagination.phtml'); ?>
	</center>
    <?
}
