<h1>Список заданий</h1>
<br />
<h2>Список список заданий работа по которым еще не звершена.</h2>
<br />
<br />

<?
foreach ($this->data as $info)
{
?>
    <h2><?= $info['title'] ?></h2>
    <table class="list" cellpadding="3" cellspacing="0" style="text-align:center;">
        <tr>
        <th class="list_head">&nbsp;</th>
        <th class="list_head">Дата создания</th>
        <th class="list_head">Крайний срок</th>
        <th class="list_head">Заголовок</th>
        <th class="list_head">Кем создано</th>
        <th class="list_head">На кого назначено</th>
        <th class="list_head">Статус</th>
        <th class="list_head">Приоритет</th>
    </tr>
    <?
    foreach ($info['values'] as $row)
    {
    ?>
    <tr id="document_row_1" class="list_tr" onMouseOver="this.setAttribute('class', 'list_tr_hover')" onMouseOut="this.setAttribute('class', 'list_tr')">
        <td class="list_row">
            <a href="/document/show-edit-task/id/<?= $row['task_id'] ?>/">
                <img border="0" width="25" height="25" src="/images/edit.png" id="decor_a" alt="Просмотр/Редактирование"/>
            </a>
        </td>
        <td class="list_row"><?= $row['create_date'] ?></td>
        <td class="list_row"><?= $row['deadline'] ?></td>
        <td class="list_row"><?= $row['title'] ?></td>
        <td class="list_row"><?= $row['assigner'] ?></td>
        <td class="list_row"><?= $row['assignees'] ?></td>
        <td class="list_row"><?= $row['status'] ?></td>
        <td class="list_row"><?= $row['priority'] ?></td>
    </tr>
    <?
    }
    ?>
    </table>
    <h2 style="text-align: right;"><a href="<?= $info['url'] ?>">&gt;&gt;&gt;&gt;&gt;</a></h2>
    <br >
    <br />
<?
}
?>